name: Conditional Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Kies een environment"
        required: true
        default: development
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  run-conditions:
    runs-on: ubuntu-latest

    steps:
      - name: Altijd tonen welke environment gekozen is
        run: echo "Gekozen environment:$ENVIRONMENT "
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}

      - name: Alleen uitvoeren bij production
        if: ${{ github.event.inputs.environment == 'production' }}
        run: echo "Deploying to production!"

      - name: Alleen uitvoeren bij development of staging
        if: ${{ github.event.inputs.environment == 'development' || github.event.inputs.environment == 'staging' }}
        run: echo "Running in test mode"
