name: Issue Trigger
on:
  issues:
     types: [opened]


jobs:
  Issue-show:
    runs-on: ubuntu-latest

    steps:
      - name: Toon title en body van het issue
        run: |
          echo "Titel van het issue: ${{ github.event.issue.title }}"
          echo "Body van het issue: ${{ github.event.issue.body }}"
